const Products = [
    {
        id: 1,
        name: "Backpack",
        price: 1000,
        collection: "Lucent",
        category: "Backpack",
        color: "Blanco",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum purus id elit viverra porta. Donec nisl nisl, blandit quis sodales in, malesuada sed leo. Phasellus tristique iaculis efficitur.",
        inStock: 5,
    },

    {
        id: 2,
        name: "Backpack",
        price: 1000,
        collection: "Lucent",
        category: "Backpack",
        color: "Negro",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum purus id elit viverra porta. Donec nisl nisl, blandit quis sodales in, malesuada sed leo. Phasellus tristique iaculis efficitur.",
        inStock: 2,
    },

    {
        id: 3,
        name: "Backpack",
        price: 1000,
        collection: "Lucent",
        category: "Backpack",
        color: "Plateado",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum purus id elit viverra porta. Donec nisl nisl, blandit quis sodales in, malesuada sed leo. Phasellus tristique iaculis efficitur.",
        inStock: 4,
    },

    {
        id: 4,
        name: "Billetera",
        price: 250, collection: "Lucent",
        category: "Accesorio",
        color: "Blanco",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum purus id elit viverra porta. Donec nisl nisl, blandit quis sodales in, malesuada sed leo. Phasellus tristique iaculis efficitur.",
        inStock: 8,
    },

    {
        id: 5,
        name: "Billetera",
        price: 250,
        collection: "Lucent",
        category: "Accesorio",
        color: "Negro",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum purus id elit viverra porta. Donec nisl nisl, blandit quis sodales in, malesuada sed leo. Phasellus tristique iaculis efficitur.",
        inStock: 9,
    },

    {
        id: 6,
        name: "Billetera",
        price: 250,
        collection: "Lucent",
        category: "Accesorio",
        color: "Plateado",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum purus id elit viverra porta. Donec nisl nisl, blandit quis sodales in, malesuada sed leo. Phasellus tristique iaculis efficitur.",
        inStock: 10,
    },

    {
        id: 7,
        name: "Clutch",
        price: 500,
        collection: "Prism",
        category: "Clutch",
        color: "Blanco",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum purus id elit viverra porta. Donec nisl nisl, blandit quis sodales in, malesuada sed leo. Phasellus tristique iaculis efficitur.",
        inStock: 3,
    },

    {
        id: 8,
        name: "Clutch",
        price: 500,
        collection: "Prism",
        category: "Clutch",
        color: "Negro",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum purus id elit viverra porta. Donec nisl nisl, blandit quis sodales in, malesuada sed leo. Phasellus tristique iaculis efficitur.",
        inStock: 2,
    },

    {
        id: 9,
        name: "Clutch",
        price: 500,
        collection: "Prism",
        category: "Clutch",
        color: "Plateado",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum purus id elit viverra porta. Donec nisl nisl, blandit quis sodales in, malesuada sed leo. Phasellus tristique iaculis efficitur.",
        inStock: 7,
    },

    {
        id: 10,
        name: "Crossbody",
        price: 750,
        collection: "Lucent",
        category: "Crossbody",
        color: "Blanco",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum purus id elit viverra porta. Donec nisl nisl, blandit quis sodales in, malesuada sed leo. Phasellus tristique iaculis efficitur.",
        inStock: 1,
    },

    {
        id: 11,
        name: "Crossbody",
        price: 750,
        collection: "Lucent",
        category: "Crossbody",
        color: "Negro",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum purus id elit viverra porta. Donec nisl nisl, blandit quis sodales in, malesuada sed leo. Phasellus tristique iaculis efficitur.",
        inStock: 6,
    },

    {
        id: 12,
        name: "Crossbody",
        price: 750,
        collection: "Lucent",
        category: "Crossbody",
        color: "Plateado",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum purus id elit viverra porta. Donec nisl nisl, blandit quis sodales in, malesuada sed leo. Phasellus tristique iaculis efficitur.",
        inStock: 5,
    },

    {
        id: 13,
        name: "Crossbody",
        price: 750,
        collection: "Prism",
        category: "Crossbody",
        color: "Blanco",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum purus id elit viverra porta. Donec nisl nisl, blandit quis sodales in, malesuada sed leo. Phasellus tristique iaculis efficitur.",
        inStock: 2,
    },

    {
        id: 14,
        name: "Crossbody",
        price: 750,
        collection: "Prism",
        category: "Crossbody",
        color: "Negro",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum purus id elit viverra porta. Donec nisl nisl, blandit quis sodales in, malesuada sed leo. Phasellus tristique iaculis efficitur.",
        inStock: 1,
    },

    {
        id: 15,
        name: "Crossbody",
        price: 750,
        collection: "Prism",
        category: "Crossbody",
        color: "Plateado",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum purus id elit viverra porta. Donec nisl nisl, blandit quis sodales in, malesuada sed leo. Phasellus tristique iaculis efficitur.",
        inStock: 7,
    },

    {
        id: 16,
        name: "Crossbody",
        price: 750,
        collection: "Slash",
        category: "Crossbody",
        color: "Blanco",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum purus id elit viverra porta. Donec nisl nisl, blandit quis sodales in, malesuada sed leo. Phasellus tristique iaculis efficitur.",
        inStock: 8,
    },

    {
        id: 17,
        name: "Crossbody",
        price: 750,
        collection: "Slash",
        category: "Crossbody",
        color: "Negro",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum purus id elit viverra porta. Donec nisl nisl, blandit quis sodales in, malesuada sed leo. Phasellus tristique iaculis efficitur.",
        inStock: 10,
    },

    {
        id: 18,
        name: "Crossbody",
        price: 750,
        collection: "Slash",
        category: "Crossbody",
        color: "Plateado",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum purus id elit viverra porta. Donec nisl nisl, blandit quis sodales in, malesuada sed leo. Phasellus tristique iaculis efficitur.",
        inStock: 4,
    },

    {
        id: 19,
        name: "Pouch",
        price: 500,
        collection: "Prism",
        category: "Pouch",
        color: "Blanco",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum purus id elit viverra porta. Donec nisl nisl, blandit quis sodales in, malesuada sed leo. Phasellus tristique iaculis efficitur.",
        inStock: 6,
    },

    {
        id: 20,
        name: "Pouch",
        price: 500,
        collection: "Prism",
        category: "Pouch",
        color: "Negro",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum purus id elit viverra porta. Donec nisl nisl, blandit quis sodales in, malesuada sed leo. Phasellus tristique iaculis efficitur.",
        inStock: 5,
    },

    {
        id: 21,
        name: "Pouch",
        price: 500,
        collection: "Prism",
        category: "Pouch",
        color: "Plateado",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum purus id elit viverra porta. Donec nisl nisl, blandit quis sodales in, malesuada sed leo. Phasellus tristique iaculis efficitur.",
        inStock: 10,
    },

    {
        id: 22,
        name: "Tote",
        price: 1000,
        collection: "Lucent",
        category: "Tote",
        color: "Blanco",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum purus id elit viverra porta. Donec nisl nisl, blandit quis sodales in, malesuada sed leo. Phasellus tristique iaculis efficitur.",
        inStock: 2,
    },

    {
        id: 23,
        name: "Tote",
        price: 1000,
        collection: "Lucent",
        category: "Tote",
        color: "Negro",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum purus id elit viverra porta. Donec nisl nisl, blandit quis sodales in, malesuada sed leo. Phasellus tristique iaculis efficitur.",
        inStock: 1,
    },

    {
        id: 24,
        name: "Tote",
        price: 1000,
        collection: "Lucent",
        category: "Tote",
        color: "Plateado",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum purus id elit viverra porta. Donec nisl nisl, blandit quis sodales in, malesuada sed leo. Phasellus tristique iaculis efficitur.",
        inStock: 7,
    },

    {
        id: 25,
        name: "Tote",
        price: 1000,
        collection: "Platinum",
        category: "Tote",
        color: "Plateado",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum purus id elit viverra porta. Donec nisl nisl, blandit quis sodales in, malesuada sed leo. Phasellus tristique iaculis efficitur.",
        inStock: 8,
    },

    {
        id: 26,
        name: "Tote",
        price: 1000,
        collection: "Platinum",
        category: "Tote",
        color: "Rosa",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum purus id elit viverra porta. Donec nisl nisl, blandit quis sodales in, malesuada sed leo. Phasellus tristique iaculis efficitur.",
        inStock: 9,
    },

    {
        id: 27,
        name: "Tote",
        price: 1000,
        collection: "Platinum",
        category: "Tote",
        color: "Verde",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum purus id elit viverra porta. Donec nisl nisl, blandit quis sodales in, malesuada sed leo. Phasellus tristique iaculis efficitur.",
        inStock: 8,
    },

    {
        id: 28,
        name: "Tote",
        price: 1000,
        collection: "Platinum",
        category: "Tote",
        color: "Violeta",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum purus id elit viverra porta. Donec nisl nisl, blandit quis sodales in, malesuada sed leo. Phasellus tristique iaculis efficitur.",
        inStock: 5,
    },

    {
        id: 29,
        name: "Tote",
        price: 1000,
        collection: "Prism",
        category: "Tote",
        color: "Blanco",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum purus id elit viverra porta. Donec nisl nisl, blandit quis sodales in, malesuada sed leo. Phasellus tristique iaculis efficitur.",
        inStock: 10,
    },

    {
        id: 30,
        name: "Tote",
        price: 1000,
        collection: "Prism",
        category: "Tote",
        color: "Negro",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum purus id elit viverra porta. Donec nisl nisl, blandit quis sodales in, malesuada sed leo. Phasellus tristique iaculis efficitur.",
        inStock: 4,
    },

    {
        id: 31,
        name: "Tote",
        price: 1000,
        collection: "Prism",
        category: "Tote",
        color: "Plateado",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum purus id elit viverra porta. Donec nisl nisl, blandit quis sodales in, malesuada sed leo. Phasellus tristique iaculis efficitur.",
        inStock: 2,
    },

    {
        id: 32,
        name: "Tote",
        price: 1000,
        collection: "Slash",
        category: "Tote",
        color: "Blanco",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum purus id elit viverra porta. Donec nisl nisl, blandit quis sodales in, malesuada sed leo. Phasellus tristique iaculis efficitur.",
        inStock: 1,
    },

    {
        id: 33,
        name: "Tote",
        price: 1000,
        collection: "Slash",
        category: "Tote",
        color: "Negro",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum purus id elit viverra porta. Donec nisl nisl, blandit quis sodales in, malesuada sed leo. Phasellus tristique iaculis efficitur.",
        inStock: 3,
    },

    {
        id: 34,
        name: "Tote",
        price: 1000,
        collection: "Slash",
        category: "Tote",
        color: "Plateado",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum purus id elit viverra porta. Donec nisl nisl, blandit quis sodales in, malesuada sed leo. Phasellus tristique iaculis efficitur.",
        inStock: 7,
    },

    {
        id: 35,
        name: "Llavero",
        price: 100,
        collection: "Lucent",
        category: "Accesorio",
        color: "Blanco",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum purus id elit viverra porta. Donec nisl nisl, blandit quis sodales in, malesuada sed leo. Phasellus tristique iaculis efficitur.",
        inStock: 10,
    },

    {
        id: 36,
        name: "Llavero",
        price: 100,
        collection: "Lucent",
        category: "Accesorio",
        color: "Negro",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum purus id elit viverra porta. Donec nisl nisl, blandit quis sodales in, malesuada sed leo. Phasellus tristique iaculis efficitur.",
        inStock: 5,
    },

    {
        id: 37,
        name: "Llavero",
        price: 100,
        collection: "Lucent",
        category: "Accesorio",
        color: "Plateado",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum purus id elit viverra porta. Donec nisl nisl, blandit quis sodales in, malesuada sed leo. Phasellus tristique iaculis efficitur.",
        inStock: 6,
    }
];